services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    volumes:
      - "./example-realm.json:/opt/keycloak/data/import/example-realm.json"
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
  simplesaml:
    container_name: simplesaml
    image: kristophjunge/test-saml-idp
    volumes:
      - "./authsources.php:/var/www/simplesamlphp/config/authsources.php"
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:8081/realms/example-realm
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:8081/realms/example-realm/broker/saml/endpoint
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:8081/realms/example-realm/broker/saml/endpoint
  example-service:
    restart: always
    build:
      context: example-service
    network_mode: "host"
    ports:
      - "3000:3000"
    container_name: example-service
